language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
gemfile:
 - Gemfile
 - gemfiles/rails4_0.gemfile
 - gemfiles/rails4_1.gemfile
 - gemfiles/rails4_2.gemfile
