language: ruby
cache: bundler
rvm:
  - 2.6.5
  - 2.7.0
  - 3.0.0

env:
- COVERALLS_SILENT=true
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

install:
  - "bundle install --jobs=3 --retry=3 --path=vendor/bundle"
  - "mkdir -p test/dummy/tmp/cache"
  - "mkdir -p test/dummy/tmp/non_default_location"

gemfile:
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails6_0.gemfile
  - gemfiles/rails6_1.gemfile
  - gemfiles/rails7_0.gemfile

jobs:
  include:
    - stage: Lint
      rvm: 3.0.0
      gemfile: gemfiles/rails7_0.gemfile
      script: bundle exec rubocop
