language: ruby
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails5_0.gemfile
